schedule: "every month"
search: False
label_prs: update
requirements:
  - requirements.txt:
      update: all
      pin: true
  - requirements-constraints.txt:
      update: insecure
      pin: true
  - docs-requirements.txt:
      pin: False
