version: '2'

services:
  db:
    # XXX How can I switch to PG 9.5?
    image: postgres:9.4
  redis-store:
    # XXX Set maxmemory and eviction policy differently here
    image: redis:3.2
  redis-cache:
    image: redis:3.2

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_CONFIGURATION
    env_file:
      - .env
    volumes:
      - $PWD:/app
    command: "true"

  web:
    extends:
      service: app
    ports:
      - "8000:8000"
    depends_on:
      - app
    links:
      - db
      - redis-store
      - redis-cache
    command: web-dev
